In [1]:
import numpy as np

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.full((2,3),10,dtype=int)

array([[10, 10, 10],
       [10, 10, 10]])

In [27]:
x=[1,2,3,4,5,6,7]
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [49]:
y=np.arange(1,17)
print(y)
print(y.shape)
print(y.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [51]:
y.reshape((8,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [53]:
y.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
print(y.ndim)

1


In [61]:
array=([2,3,4,5,6,7,7,8,9,0,1])
array[2]

4